---
#tasks for wordpress
- stat:
    path: /var/www/html/wordpress
  register: path

- name: Download WordPress
  get_url: 
    url:  https://wordpress.org/latest.tar.gz
    dest: /tmp/wordpress-latest.tar.gz 
  when : path.stat.isdir is not defined

- name: Extract WordPress
  unarchive:
    src: /tmp/wordpress-latest.tar.gz
    dest: /tmp
    owner: www-data
    group: www-data
    copy: no
  when : path.stat.isdir is not defined

- name: Move WordPress install files
  command: mv /tmp/wordpress /var/www/html/wordpress
  when : path.stat.isdir is not defined

- name: Change mode wordpress
  command: chmod -R 755 /var/www/html/wordpress/
  when : path.stat.isdir is not defined

- name: Add wp-config
  template: "src=wp-config.php dest=/var/www/html/wordpress/wp-config.php"

- name: Update WordPress config file
  lineinfile:
    dest: "/var/www/html/wordpress/wp-config.php"
    regexp: "{{ item.regexp }}"
    line: "{{ item.line }}"
  with_items:
    - {'regexp': "define\\('DB_NAME', '(.)+'\\);", 'line': "define('DB_NAME', '{{wp_db_name}}');"}
    - {'regexp': "define\\('DB_USER', '(.)+'\\);", 'line': "define('DB_USER', '{{wp_db_user}}');"}
    - {'regexp': "define\\('DB_PASSWORD', '(.)+'\\);", 'line': "define('DB_PASSWORD', '{{wp_db_password}}');"}
    - {'regexp': "define\\('DB_PASSWORD', '(.)+'\\);", 'line': "define('DB_PASSWORD', '{{wp_db_host}}');"}

- name: Configure new website
  copy:
    src: ../../nginx/templates/default
    dest: /etc/nginx/sites-available/default  

- name: Restart nginx & php
  command: systemctl restart nginx.service php7.2-fpm.service


