---
# tasks file for nginx

- name: Install nginx web server 
  apt:
    name: nginx
    state: present
    update_cache: true

- name: nginx configuration
  template: "src=nginx.conf dest=/etc/nginx/nginx.conf"

- name: restart nginx
  service:
    name: nginx
    state: restarted

- name: enable nginx
  command: systemctl enable nginx

